config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'

Diaspora::Application.routes.draw do
  resources :post_report, :except => [:edit]

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares

  resources :status_messages, :only => [:new, :create]

  resources :posts do
    member do
      get :next
      get :previous
      get :interactions
    end

    resources :poll_participations, :only => [:create]

    resources :likes, :only => [:create, :destroy, :index ]
    resources :participations, :only => [:create, :destroy, :index]
    resources :comments, :only => [:new, :create, :destroy, :index]
  end



  get 'p/:id' => 'posts#show', :as => 'short_post'
  get 'posts/:id/iframe' => 'posts#iframe', :as => 'iframe'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
  get "participate" => "streams#activity", :as => "activity_stream" # legacy
  get "explore" => "streams#multi", :as => "stream"                 # legacy

  get "activity" => "streams#activity", :as => "activity_stream"
  get "stream" => "streams#multi", :as => "stream"
  get "public" => "streams#public", :as => "public_stream"
  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
  get "liked" => "streams#liked", :as => "liked_stream"
  get "commented" => "streams#commented", :as => "commented_stream"
  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects do
    put :toggle_contact_visibility
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, :except => [:index, :show] do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  get 'notifications/read_all' => 'notifications#read_all'
  resources :notifications, :only => [:index, :update] do
  end

  resources :tags, :only => [:index]

  resources "tag_followings", :only => [:create, :destroy, :index]

  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :getting_started_completed
    get :export
    get :export_photos
  end

  controller :users do
    get 'public/:username'          => :public,           :as => 'users_public'
    match 'getting_started'         => :getting_started,  :as => 'getting_started'
    match 'privacy'                 => :privacy_settings, :as => 'privacy_settings'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,    :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :passwords     => "passwords",
                                      :sessions      => "sessions"}

  #legacy routes to support old invite routes
  get 'users/invitation/accept' => 'invitations#edit'
  get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  get 'users/invitations' => 'invitations#new', :as => 'new_user_invitation'
  post 'users/invitations' => 'invitations#create', :as => 'new_user_invitation'

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match :user_search
    get   :admin_inviter
    get   :weekly_user_stats
    get   :correlations
    get   :stats, :as => 'pod_stats'
    get   "add_invites/:invite_code_id" => 'admins#add_invites', :as => 'add_invites'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts,           :except => [:update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"
    get :hovercard

    member do
      get :last_post
    end

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile'
  get '/u/:username/profile_photo' => 'users#user_photo'


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end



  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      match ':provider/callback' => :create
      match :failure
    end
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end

  namespace :api do
    namespace :v0 do
      get "/users/:username" => 'users#show', :as => 'user'
      get "/tags/:name" => 'tags#show', :as => 'tag'
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  # help
  get 'help' => 'help#faq', :as => 'help'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")
  
  #Statistics
  get :statistics, controller: :statistics

  # Startpage
  root :to => 'home#show'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  include Diaspora::Federated::Base
  include Diaspora::Guid

  xml_attr :subject
  xml_attr :created_at
  xml_attr :messages, :as => [Message]
  xml_reader :diaspora_handle
  xml_reader :participant_handles

  has_many :conversation_visibilities, :dependent => :destroy
  has_many :participants, :class_name => 'Person', :through => :conversation_visibilities, :source => :person
  has_many :messages, :order => 'created_at ASC'

  belongs_to :author, :class_name => 'Person'

  validate :max_participants

  def max_participants
    errors.add(:max_participants, "too many participants") if participants.count > 20
  end

  accepts_nested_attributes_for :messages

  def recipients
    self.participants - [self.author]
  end

  def diaspora_handle
    self.author.diaspora_handle
  end

  def diaspora_handle= nh
    self.author = Webfinger.new(nh).fetch
  end

  def first_unread_message(user)
    if visibility = self.conversation_visibilities.where(:person_id => user.person.id).where('unread > 0').first
      self.messages.all[-visibility.unread]
    end
  end

  def public?
    false
  end

  def participant_handles
    self.participants.map{|p| p.diaspora_handle}.join(";")
  end
  def participant_handles= handles
    handles.split(';').each do |handle|
      self.participants << Webfinger.new(handle).fetch
    end
  end

  def last_author
    return unless @last_author.present? || self.messages.size > 0
    @last_author_id ||= self.messages.pluck(:author_id).last
    @last_author ||= Person.includes(:profile).where(id: @last_author_id).first
  end

  def subject
    self[:subject].blank? ? "no subject" : self[:subject]
  end

  def subscribers(user)
    self.recipients
  end

  def receive(user, person)
    cnv = Conversation.find_or_create_by_guid(self.attributes)

    self.participants.each do |participant|
      ConversationVisibility.find_or_create_by_conversation_id_and_person_id(cnv.id, participant.id)
    end

    self.messages.each do |msg|
      msg.conversation_id = cnv.id
      received_msg = msg.receive(user, person)
      Notification.notify(user, received_msg, person) if msg.respond_to?(:notification_type)
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  layout ->(c) { request.format == :mobile ? "application" : "with_header" }
  use_bootstrap_for :index, :show, :new

  respond_to :html, :mobile, :json, :js

  def index
    @conversations = current_user.conversations.paginate(
      :page => params[:page], :per_page => 15)

    @visibilities = current_user.conversation_visibilities.paginate(
      :page => params[:page], :per_page => 15)

    @conversation = Conversation.joins(:conversation_visibilities).where(
      :conversation_visibilities => {:person_id => current_user.person_id, :conversation_id => params[:conversation_id]}).first

    @unread_counts = {}
    @visibilities.each { |v| @unread_counts[v.conversation_id] = v.unread }

    @first_unread_message_id = @conversation.try(:first_unread_message, current_user).try(:id)

    @authors = {}
    @conversations.each { |c| @authors[c.id] = c.last_author }

    @ordered_participants = {}
    @conversations.each { |c| @ordered_participants[c.id] = (c.messages.map{|m| m.author}.reverse + c.participants).uniq }

    respond_with do |format|
      format.html
      format.json { render :json => @conversations, :status => 200 }
    end
  end

  def create
    # Can't split nil
    if params[:contact_ids]
      person_ids = current_user.contacts.where(id: params[:contact_ids].split(',')).pluck(:person_id)
    end

    opts = params.require(:conversation).permit(:subject)
    opts[:participant_ids] = person_ids
    opts[:message] = { text: params[:conversation][:text] }
    @conversation = current_user.build_conversation(opts)

    @response = {}
    if person_ids.present? && @conversation.save
      Postzord::Dispatcher.build(current_user, @conversation).post
      @response[:success] = true
      @response[:message] = I18n.t('conversations.create.sent')
      @response[:conversation_id] = @conversation.id
    else
      @response[:success] = false
      @response[:message] = I18n.t('conversations.create.fail')
      if person_ids.blank?
        @response[:message] = I18n.t('conversations.create.no_contact')
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    if @conversation = current_user.conversations.where(id: params[:id]).first

      @first_unread_message_id = @conversation.first_unread_message(current_user).try(:id)
      if @visibility = ConversationVisibility.where(:conversation_id => params[:id], :person_id => current_user.person.id).first
        @visibility.unread = 0
        @visibility.save
      end

      respond_to do |format|
        format.html { redirect_to conversations_path(:conversation_id => @conversation.id) }
        format.js
        format.json { render :json => @conversation, :status => 200 }
      end
    else
      redirect_to conversations_path
    end
  end

  def new
    all_contacts_and_ids = Contact.connection.select_rows(
      current_user.contacts.where(:sharing => true).joins(:person => :profile).
        select("contacts.id, profiles.first_name, profiles.last_name, people.diaspora_handle").to_sql
    ).map{|r| {:value => r[0], :name => Person.name_from_attrs(r[1], r[2], r[3]).gsub(/(")/, "'")} }

    @contact_ids = ""

    @contacts_json = all_contacts_and_ids.to_json
    if params[:contact_id]
      @contact_ids = current_user.contacts.find(params[:contact_id]).id
    elsif params[:aspect_id]
      @contact_ids = current_user.aspects.find(params[:aspect_id]).contacts.map{|c| c.id}.join(',')
    end
    if session[:mobile_view] == true && request.format.html?
    render :layout => true
    elsif
    render :layout => false
    end
  end
end

app/views/conversations/_conversation.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.conversation-wrapper{ :"data-conversation-path" => conversation_path(conversation) }
  .stream_element.conversation{:data=>{:guid=>conversation.id}, :class => ('unread' if unread_counts[conversation.id].to_i > 0)}
    .media
      .img
        - other_participants = ordered_participants[conversation.id] - [current_user.person]
        - if other_participants.first.present?
          = person_image_tag(other_participants.first)
          - if other_participants.count > 1
            .participants_count
              = other_participants.count - 1

      .bg
        .badge.badge-dafault.message_count
          = conversation.messages.size
        - unread_count = unread_counts[conversation.id].to_i
        - if unread_count > 0
          .badge.badge-important.unread_message_count
            = unread_count
        .subject
          %div{ :class => direction_for(conversation.subject) }
            = conversation.subject
        .timestamp
          = timeago(conversation.updated_at)
        .last_author
          - if authors[conversation.id].present?
            = authors[conversation.id].name
        .last_message
          - if conversation.messages.present?
            = '»' + conversation.messages.last.text + '«'
        - if other_participants.count > 1
          .participants
            - other_participants.drop(1).take(15).each do |participant|
              = person_image_tag(participant)

app/views/conversations/_conversation.mobile.haml
%a.conversation{ :href => conversation_path(conversation) }
  .stream_element.conversation{:data=>{:guid=>conversation.id}, :class => ('unread' if unread_counts[conversation.id].to_i > 0)}
    .media
      .img
        = person_image_tag(conversation.author)

      .bg
        = render(:partial => 'conversation_subject',
                  :locals => { :conversation => conversation,
                               :unread_count => unread_counts[conversation.id].to_i })

        .last_author
          .timestamp
            = timeago(conversation.updated_at)

          - if authors[conversation.id].present?
            = authors[conversation.id].name

          - if conversation.participants.size > 2
            %span.participant_count
              = "(+#{conversation.participants.size - 1})"

app/views/conversations/_conversation_subject.haml
.subject
  .badge.badge-dafault.message_count
    = conversation.messages.size
  - if unread_count > 0
    .badge.badge-important.unread_message_count
      = unread_count

  %div{ :class => direction_for(conversation.subject) }
    = conversation.subject[0..30]

app/views/conversations/_show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.conversation_participants
  = link_to(content_tag(:div, nil, :class => 'icons-deletelabel'),
            conversation_visibility_path(conversation),
            :method => 'delete',
            :data => { :confirm => "#{t('.delete')}?" },
            :title => t('.delete'),
            :class => 'close_conversation')

  %h3{ :class => direction_for(conversation.subject) }
    = conversation.subject

  - for participant in conversation.participants
    = person_image_link(participant, :size => :thumb_small)

.stream
  = render :partial => 'messages/message', :collection => conversation.messages

  .stream_element.new_message
    .media
      .img
        = owner_image_tag(:thumb_small)

      .bd
        = form_for [conversation, Message.new] do |message|
          = message.text_area :text, :class => 'span12', :rows => 5, :tabindex => 1
          = message.submit t('.reply').capitalize, 'data-disable-with' => t('.replying'), :class => 'btn btn-primary creation', :tabindex => 2

app/views/conversations/_show.mobile.haml
-# Copyright (c) 2010-2011, Diaspora Inc. This file is
-# licensed under the Affero General Public License version 3 or later. See
-# the COPYRIGHT file.

.conversation_participants
  .right
    = link_to(image_tag('deletelabel.png'), conversation_visibility_path(conversation), :method => 'delete', :data => { :confirm => "#{t('.delete')}?" }, :class => "remove")

  %h3{ :class => direction_for(conversation.subject) }
    = conversation.subject

  - for participant in conversation.participants
    = person_image_link(participant, :size => :thumb_small)

.span-15.last
  .stream
    = render :partial => 'messages/message', :collection => conversation.messages

    .stream_element.new_message
      .media
        .img
          = owner_image_tag(:thumb_small)

        .bd
          = form_for [conversation, Message.new] do |message|
            = message.text_area :text, :rows => 5, :tabindex => 1
            = message.submit t('.reply').capitalize, 'data-disable-with' => t('.replying'), :class => 'button creation', :tabindex => 2

app/views/conversations/create.js.erb
var response = <%= raw @response.to_json %>;
<% if session[:mobile_view] %>
  window.location.href = "<%= conversations_path(conversation_id: @conversation.id) %>";
<% else %>
  Diaspora.page.flashMessages.render({ 'success':response.success, 'notice':response.message });
  if(response.success){
    $("#new_conversation").removeClass('form_do_not_clear').clearForm();
    $.facebox.close();
    window.location.href = "<%= conversations_path(conversation_id: @conversation.id) %>";
  }
<% end %>

app/views/conversations/index.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- content_for :head do
  = javascript_include_tag :inbox

- content_for :page_title do
  = t('.conversations_inbox')

.container-fluid.conversations_container
  .row-fluid
    .span4
      #left_pane
        #left_pane_header
          %h3
            .pull-right
              = link_to t('.new_conversation'), new_conversation_path, :class => 'btn btn-default', :rel => 'facebox'
            = t('.inbox')

        #conversation_inbox
          .stream.conversations
            - if @conversations.count > 0
              = render :partial => 'conversations/conversation', :collection => @conversations, :locals => {:authors => @authors, :ordered_participants => @ordered_participants, :unread_counts => @unread_counts}
            - else
              #no_conversations
                = t('.no_messages')
            = will_paginate @conversations, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer


    .span8
      .stream_container
        #conversation_show
          - if @conversation
            = render 'conversations/show', :conversation => @conversation
          - else
            #no_conversation_text
              = t('.no_conversation_selected')
            #no_conversation_controls
              = link_to t('.create_a_new_conversation'), new_conversation_path, :rel => 'facebox'

app/views/conversations/index.mobile.haml
-#   Copyright (c) 2010-2012, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.right
  = link_to t('.new_conversation'), new_conversation_path, :class => 'btn'

- flash.each do |name, msg|
  %div{:id => "flash_#{name}", :class => "expose"}
    .message= msg
  .stream
    %p{:class => "conversation_#{name}"}= msg

%h3
  = t('.inbox')

#conversation_inbox
  .stream.conversations
    - if @conversations.count > 0
      = render :partial => 'conversations/conversation', :collection => @conversations, :locals => {:authors => @authors, :unread_counts => @unread_counts}
    - else
      %br
      %br
      %br
      %br
      %div{:style => 'text-align:center;'}
        %i
          = t('.no_messages')

  = will_paginate @conversations, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer

app/views/conversations/new.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- if in_mobile_view?
  = javascript_include_tag :jquery
  = javascript_include_tag :mobile

:javascript
  $(document).ready(function () {
    var data = $.parseJSON( "#{escape_javascript(@contacts_json)}" ),
        autocompleteInput = $("#contact_autocomplete");

    autocompleteInput.autoSuggest(data, {
      selectedItemProp: "name",
      searchObjProps: "name",
      asHtmlID: "contact_ids",
      retrieveLimit: 10,
      minChars: 1,
      keyDelay: 0,
      startText: '',
      emptyText: '#{t('no_results')}',
      preFill: [{name : "#{h params[:name]}",
                 value : "#{@contact_ids}"}]
      });
    autocompleteInput.focus();
  });

.span6#new_conversation_pane
  .span5#facebox_header
    %h3
      = t('conversations.index.new_conversation')

  = form_for Conversation.new, html: {class: "new_conversation form_do_not_clear"}, remote: true do |conversation|

    .span1
      %h4
        = t('.to')
    .span4
      = text_field_tag "contact_autocomplete"
    .clearfix
    %br
    .span1
      %h4
        = t('.subject')
    .span4
      = conversation.text_field :subject
    %br
    .span4.offset1
      = text_area_tag "conversation[text]", '', :rows => 5
    .clearfix
    .bottom_submit_section
      = conversation.submit t('.send'), 'data-disable-with' => t('.sending'), :class => 'button creation'

app/views/conversations/show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= render 'show', :conversation => @conversation

app/views/conversations/show.js.erb
$('#conversation_show').html("<%= escape_javascript(render('conversations/show', :conversation => @conversation)) %>");

$(".stream_element", "#conversation_inbox").removeClass('selected');
$(".stream_element[data-guid='<%= @conversation.id %>']", "#conversation_inbox").addClass('selected');
$(".stream_element[data-guid='<%= @conversation.id %>']", "#conversation_inbox").find(".unread_message_count").remove()

$('time.timeago').each(function(i,e) {
  var jqe = $(e);
  jqe.attr('data-original-title', new Date(jqe.attr('datetime')).toLocaleString());
});

if ($('#first_unread') > 0) {
  $("html").scrollTop($('#first_unread').offset().top-45);
}

$(".timeago").tooltip();
$("time.timeago").timeago();

$('time.timeago').each(function(i,e) {
  var jqe = $(e);
  jqe.attr('title', '');
});